language: scala
env:
   - PLAY_VERSION=2.0.1
scala:
   - 2.9.1
before_script: 
   - wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
   - unzip -q play-${PLAY_VERSION}.zip 
   - export PATH=$PATH:play-${PLAY_VERSION}
script:
   - play test
